name: Check

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: make setup

      - name: Run api tests
        run: |
          make api_test

      - name: Run api lint and format checks
        run: |
          make ruff_check

      - name: Run ui tests
        working-directory: ./ui
        run: make ui_test
